version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # sql para crear base y tablas
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # sql para poblar tablas
      - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      # script ejecución de inicialización
      - ./after_create.sh:/docker-entrypoint-initdb.d/after_create.sh